# This workflow will install the edgepi-rpc server and test interaction

name: Integration tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Integration Tests
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        if: ${{ github.event_name  == 'pull_request'}}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout
        if: ${{ github.event_name  == 'push'}}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.0"
          cache: "npm"

      - name: Install npm@9.8.0
        run: npm i -g npm@9.8.0

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Install server
        run: 
          wget -qO - https://deb.edgepi.com/edgepi-release.gpg | sudo gpg --dearmor -o /usr/share/keyrings/edgepi-release.gpg
          sudo tee /etc/apt/sources.list.d/edgepi.list >/dev/null <<'EOF'deb [arch=arm64, signed-by=/usr/share/keyrings/edgepi-release.gpg] https://deb.edgepi.com/nightly bullseye nightly EOF
          sudo apt update
          sudo apt install edgepi-rpc-server
     
      - name: Test with jest
        run: |
          npm run test tests/integration
