# Tests this modules interaction with edgepi-rpc-server on the runner

name: Integration tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Integration Tests
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        if: ${{ github.event_name  == 'pull_request'}}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout
        if: ${{ github.event_name  == 'push'}}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.0"
          cache: "npm"

      - name: Install npm@9.8.0
        run: npm i -g npm@9.8.0

      # For zmq work around
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Install dependencies
        run: npm ci --prefer-offline

     
      - name: Test with jest
      # TODO: fix sudo issue
        run: |
          sudo npm run test tests/integration
