name: Unit testing
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.0"
          cache: "npm"

      - name: Install npm@9.8.0
        run: npm i -g npm@9.8.0

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Test
        run: npm run test